# Generated by Django 6.1.1 on 2026-09-25 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text='Identificativo utente / numero WhatsApp', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(default='IDLE', max_length=30)),
                ('temp_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('ALTRO', 'Altro')], default='AUTO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bot.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(choices=[('INSURANCE', 'Assicurazione'), ('TAX', 'Bollo')], max_length=20)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='bot.vehicle')),
            ],
        ),
    ]
