# Generated by Django 6.1.1 on 2026-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='deadline_type',
            field=models.CharField(choices=[('INSURANCE', 'Assicurazione'), ('TAX', 'Bollo'), ('NOT', 'Revisione')], max_length=20),
        ),
    ]
