# Generated by Django 6.1.1 on 2026-09-29 08:37

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_deadline_deadline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_year',
            field=models.PositiveIntegerField(blank=True, help_text='Anno di immatricolazione', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wa_id',
            field=models.CharField(help_text='Identificativo utente (Telegram ID / WhatsApp)', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('user', 'plate')},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('INSURANCE', 'Assicurazione'), ('TAX', 'Bollo'), ('NOT', 'Revisione'), ('MAINTENANCE', 'Tagliando / Manutenzione'), ('REPAIR', 'Riparazione'), ('PARTS', 'Ricambi / Accessori'), ('FUEL', 'Carburante'), ('OTHER', 'Altro')], default='MAINTENANCE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Costo in Euro (€)', max_digits=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, help_text='Es. Cambio gomme, scarico, pastiglie freni', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='bot.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
